services:
  pbnsolve-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pbnsolve-api:latest
    container_name: pbnsolve-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - LOG_LEVEL=info
